name: DevSecOps Pipeline (UAS)

on:
  push:
    branches:
      - main

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies (NO TEST)
      run: |
        npm install --ignore-scripts

    # ======================
    # SAST
    # ======================
    - name: SAST - npm audit
      run: |
        npm audit --audit-level=high || true

    # ======================
    # Install Trivy
    # ======================
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
        trivy --version

    # ======================
    # SCA
    # ======================
    - name: SCA - Trivy filesystem scan
      run: |
        trivy fs . || true

    # ======================
    # Build & Scan Container
    # ======================
    - name: Build Docker image
      run: |
        docker build -t juice-shop:latest .

    - name: Container Scan - Trivy image
      run: |
        trivy image juice-shop:latest || true

    # ======================
    # DAST
    # ======================
    - name: Run OWASP Juice Shop
      run: |
        docker run -d -p 3000:3000 bkimminich/juice-shop
        sleep 30

    - name: DAST - OWASP ZAP
      run: |
        docker run -t owasp/zap2docker-stable zap-baseline.py \
        -t http://host.docker.internal:3000 || true
