name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    # =========================
    # SAST
    # =========================
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies (NO TEST)
      run: npm install --ignore-scripts

    - name: SAST - npm audit
      run: |
        npm audit --audit-level=high || true

    # =========================
    # SCA
    # =========================
    - name: Install Trivy (Official Script)
      run: |
      sudo apt-get update
      sudo apt-get install -y curl
      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
      trivy --version

    - name: Trivy Filesystem Scan
      run: trivy fs . || true

    # =========================
    # BUILD CONTAINER
    # =========================
    - name: Build Docker Image
      run: docker build -t juice-shop:latest .

    - name: Trivy Image Scan
      run: trivy image juice-shop:latest || true

    # =========================
    # DAST
    # =========================
    - name: Run OWASP Juice Shop
      run: |
        docker run -d -p 3000:3000 bkimminich/juice-shop
        sleep 20

    - name: DAST - OWASP ZAP Baseline
      run: |
        docker run -t owasp/zap2docker-stable zap-baseline.py \
        -t http://host.docker.internal:3000 || true
