name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    # 🔐 SAST
    - name: SAST - npm audit
      run: |
        npm audit --audit-level=high || true

    # 🔐 SCA
    - name: Install Trivy
      run: |
        sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.48.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.48.0_Linux-64bit.deb

    - name: Trivy FS Scan
      run: trivy fs .

    # 🐳 Build Docker Image
    - name: Build Docker Image
      run: docker build -t juice-shop:latest .

    # 🐳 Container Scan
    - name: Trivy Image Scan
      run: trivy image juice-shop:latest

    # 🌐 DAST
    - name: Run OWASP ZAP Baseline
      run: |
        docker run -t owasp/zap2docker-stable zap-baseline.py \
        -t http://host.docker.internal:3000 || true
